---
actions:
  to: kubernetes/overlays/local/kustomization.yaml
---
images:
  - name: docker.io/markpollack/helloworld-java-spring  #used for Kustomize matching
    newName: dev.local/{{artifactId}}
    newTag: 0.0.1-SNAPSHOT
resources:
  - ../base
patchesJson6902:
  - target:
      group: serving.knative.dev
      version: v1
      kind: Service
      name: helloworld-java-spring
    path: patch-env.yaml
