---
actions:
  to: skaffold.yaml
---
apiVersion: skaffold/v2alpha2
kind: Config
profiles:
  - name: local
    build:
      artifacts:
        - image: dev.local/{{artifactId}}
          jib:
            args:
              - -Plocal
              - -DskipTests=true
#          buildpack:
#            builder: "cloudfoundry/cnb:cflinuxfs3"
      tagPolicy:
        sha256: {}
      local:
        push: false
    deploy:
      kustomize:
        paths:
          - kubernetes/overlays/local
#
# Will be using k8s yaml files for services
#
  - name: local-services
    deploy:
      kustomize:
        paths:
          - kubernetes/overlays/local-services/mysql
